version: '3.7'

services:
    mariadb:
        # The DRLMv3 database config options for development and testing purposes can be
        # specified settings in something like mydrlm.cnf under ${PWD}/db/conf folder.
        # Tu make use of TLS put the certificates in ${PWD}/db/tls folder and edit ${PWD}/db/conf/mydrlm.cnf
        # with:
        #  [mysqld]
        #  ssl
        #  ssl-ca = /tls/ca-cert.pem
        #  ssl-key = /tls/dbs-key.pem
        #  ssl-cert = /tls/dbs-cert.pem
        #
        # A good strong defaults sould be with REQUIRE ISSUER.
        #
        # On the client side you need to care about client certificates on mysql client utility for debugging or in
        # DRLM config itself to be able to connect to the Database.
        # For example in mysql client config file:
        #  [mysql]
        #  ssl-ca = /path/to/ca-cert.pem
        #  ssl-key = /path/to/dbcli-key.pem
        #  ssl-cert = /path/to/dbcli-cert.pem
        #
        # TODO:
        # The point will be to use some PKI infra to autogenerate all the TLS certificates, I'm looking
        # at cfssl to get all required certs automatically.

        image: dr3dev-db:${MARIADB_VERSION}
        container_name: mariadb
        hostname: mariadb
        domainname: dr3dev.local
        environment:
            MYSQL_ROOT_PASSWORD: drlm3db
            MYSQL_DATABASE: drlm3
            MYSQL_USER: drlm3
            MYSQL_PASSWORD: drlm3db
        restart: on-failure
        volumes:
            - ${PWD}/files/db/data:/var/lib/mysql
            - ${PWD}/files/db/conftls:/etc/mysql/conf.d
            - ${PWD}/files/tls:/tls
        ports:
            - "33060:3306"
        networks:
            - dr3dev

    minio:
        image: dr3dev-minio:latest
        container_name: minio
        hostname: minio
        domainname: dr3dev.local
        environment:
            MINIO_ACCESS_KEY: drlm3minio
            MINIO_SECRET_KEY: drlm3minio
        restart: on-failure
        volumes:
            - ${PWD}/files/minio/data:${HOME}/.minio/data
            - ${PWD}/files/tls/minio:${HOME}/.minio/certs
        ports:
            - "9443:9443"
        networks:
            - dr3dev
        command: server --address ":9443" .minio/data


networks:
    dr3dev:
        external: true
