version: '3.7'

services:

    tls:
        image: dr3dev-tls:latest
        container_name: tls
        hostname: tls
        domainname: dr3dev.local
        restart: on-failure
        volumes:
            - ${PWD}/files/tls:/tls
        ports:
            - "8888:8888"
        networks:
            - dr3dev

networks:
    dr3dev:
        external: true

