version: '3.7'

services:

    tls:
        # cfssl CA server
        # 
        image: mytls:latest
        container_name: tls
        hostname: tls
        domainname: dr3dev.local
#        environment:
        restart: on-failure
        volumes:
            - ${PWD}/files/tls:/tls
        ports:
            - "8888:8888"
              #        network_mode: "bridge"
        networks:
            - dr3dev

networks:
    dr3dev:
        external: true

